version: '{build}'
image: Visual Studio 2015
platform:
  - x86
  - x64
configuration:
  - Release
environment:
  PROJECT: log4cpp
  CMAKE_PROJECT: LOG4CPP
  VERSION: 1.1.1-1

install:
  - ps: |
      Start-FileDownload https://sourceforge.net/projects/log4cpp/files/log4cpp-1.1.x%20%28new%29/log4cpp-1.1/log4cpp-1.1.1.tar.gz/download log4cpp-1.1.1.tar.gz
      tar -x -f log4cpp-1.1.1.tar.gz -C c:\projects

before_build: 
  - ps: |
      ${env:BUILD_DIRECTORY}="${env:APPVEYOR_BUILD_FOLDER}\build"
      ${env:INSTALL_DIRECTORY}="${env:APPVEYOR_BUILD_FOLDER}\${env:PROJECT}"
      New-Item -Path "${env:BUILD_DIRECTORY}" -ItemType "directory"
      cd "${env:BUILD_DIRECTORY}"
      ${generator} = "Visual Studio 14 2015"
      if (${env:PLATFORM} -eq "x64") { ${generator} = "${generator} Win64" }
      cmake -G "${generator}" -DCMAKE_INSTALL_PREFIX="${env:INSTALL_DIRECTORY}" "C:\projects\${env:PROJECT}"

build_script:
  - ps: |
      msbuild "${env:BUILD_DIRECTORY}\${CMAKE_PROJECT}.sln" /m /v:minimal
      msbuild "${env:BUILD_DIRECTORY}\INSTALL.vcxproj" /m /v:minimal

after_build:
  - ps: |
      cd "${env:APPVEYOR_BUILD_FOLDER}"
      7z a "${env:PROJECT}_${env:VERSION}_${env:PLATFORM}.zip" "${env:PROJECT}"

artifacts:
  - path: $(PROJECT)_$(VERSION)_$(platform).zip

deploy:
  release: v$(VERSION)
  description: "v$(VERSION)"
  provider: GitHub
  auth_token:
    secure: Stag2HnDJZFOF5/29yUlXQNlShCTIbAaAH/JLNnO7pb1AUIPGSnNJI4BykbCxVp2
  artifact: /.*\.zip/
  on:
    branch: master
    appveyor_repo_tag: true

